<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V9897AD" failures="1" tests="6" name="Test" time="18.826" errors="0" timestamp="2023-10-05T23:13:50 IST">
  <testcase classname="com.Task.RetryAnalyzer" name="TestHomePage" time="6.816">
    <skipped/>
  </testcase> <!-- TestHomePage -->
  <testcase classname="com.Task.RetryAnalyzer" name="TestHomePage" time="4.504">
    <skipped/>
  </testcase> <!-- TestHomePage -->
  <testcase classname="com.Task.RetryAnalyzer" name="TestHomePage" time="3.868">
    <skipped/>
  </testcase> <!-- TestHomePage -->
  <testcase classname="com.Task.RetryAnalyzer" name="TestHomePage" time="3.523">
    <failure type="java.lang.AssertionError" message="expected [My Demo page] but found [Your Store]">
      <![CDATA[java.lang.AssertionError: expected [My Demo page] but found [Your Store]
at com.Task.RetryAnalyzer.TestHomePage(RetryAnalyzer.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestHomePage -->
  <testcase classname="com.Task.RetryAnalyzer" name="goToLogin" time="0.0">
    <skipped/>
  </testcase> <!-- goToLogin -->
  <testcase classname="com.Task.RetryAnalyzer" name="returningUser" time="0.0">
    <skipped/>
  </testcase> <!-- returningUser -->
</testsuite> <!-- Test -->
